
server:
  port: 8181

spring:
  devtools:
    remote:
      restart:
        enabled: true
  datasource:
    url: jdbc:h2:~/blacklabel
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

info:
  module-name: blacklabel-mobility-api
  log-file-name: app.log

# logging
logging.config: classpath:logging/logback-local.xml

#Mybatis 설정
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true